theme = "noctis-hq"

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.file-picker]
hidden = false

[keys.normal]
p = "paste_before"
P = "paste_after"
C-s = [
    "save_selection",
    "select_all",
    # Delete trailing whitespace from end of each line
    ":pipe sed 's/[ \t]*$//'",
    # Delete trailing blank lines (including whitespace) at end of the buffer
    ":pipe awk '/^\\s*$/ {b=b $0 \"\\n\"; next;} {printf \"%s\",b; b=\"\"; print;}'",
    "collapse_selection",
    "jump_backward",
    # It writes but introduces a phantom change at the moment
    ":write",
]
# C-s = ":w"
C-p = ":open ~/.config/helix/config.toml"
S-left = "extend_char_left"
S-right = "extend_char_right"
S-up = "extend_line_up"
S-down = "extend_line_down"
C-left = ["move_prev_word_start", "move_char_left", "move_char_right"]
C-right = ["move_next_word_start", "move_char_left", "move_char_right"]
C-up = "move_line_up"
C-down = "move_line_down"
C-S-left = ["select_mode", "extend_prev_word_start"]
C-S-right = ["select_mode", "extend_next_word_end"]
C-S-up = ["select_mode", "extend_line_up"]
C-S-down = ["select_mode", "extend_line_down"]

[keys.normal."space"]
a = "jump_backward"
d = "jump_forward"
p = "paste_clipboard_before"
P = "paste_clipboard_after"
q = "code_action"

[keys.select]
C-left = "extend_prev_word_start"
C-right = "extend_next_word_start"
C-up = "extend_line_up"
C-down = "extend_line_down"
C-S-left = "extend_prev_word_start"
C-S-right = "extend_next_word_end"
C-S-up = "extend_line_up"
C-S-down = "extend_line_down"

[keys.insert]
C-left = ["move_prev_word_start", "move_char_left", "move_char_right"]
C-right = ["move_next_word_start", "move_char_left", "move_char_right"]
C-up = "move_line_up"
C-down = "move_line_down"
